{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 401)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_user_update.TestUserUpdate object at 0x106cb8f20>\n\n    @allure.title('Проверка ответа на запрос изменения данных неаутентифицированного пользователя')\n    def test_update_user_unauthenticated_expected_error(self):\n        response = requests.patch(Urls.user_update, headers=Urls.headers, data=TestUserUpdate.updated_user_data)\n>       assert response.status_code == 401 and response.json() == {'success': False,\n                                                                   'message': 'You should be authorised'}\nE       assert (400 == 401)\nE        +  where 400 = <Response [400]>.status_code\n\ntests/test_user_update.py:24: AssertionError"}, "start": 1726425438364, "stop": 1726425438743, "uuid": "0afde10b-461c-4ea9-9c71-caf719d5af23", "historyId": "15ddd7987c2e5999e579e59a038213af", "testCaseId": "15ddd7987c2e5999e579e59a038213af", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "NB-ISC-69172.local"}, {"name": "thread", "value": "13839-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}