{"name": "Проверка ответа при запросе на получение списка заказов неаутентифицированного пользователя", "status": "passed", "start": 1726425433456, "stop": 1726425433852, "uuid": "6e84cb1e-dce6-4d98-90ba-49ba20c36ef8", "historyId": "d932a420574a8af1ba53e8754c88e341", "testCaseId": "d932a420574a8af1ba53e8754c88e341", "fullName": "tests.test_get_user_orders.TestGetOrders#test_get_orders_unauthenticated_user_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "NB-ISC-69172.local"}, {"name": "thread", "value": "13839-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}